#!/bin/sh
tty="$1"
shift
exec <"/dev/$tty" >"/dev/$tty" 2>"/dev/$tty"
echo
echo -e " \x1b[36m▼\x1b[0m Loading grommunio console user interface"
echo
if [ -d /usr/libexec/grommunio-cui ]; then
	PYTHONPATH="/usr/libexec/grommunio-cui/cui" exec "/usr/bin/python3" \
		"/usr/libexec/grommunio-cui/__init__.py"
fi
