#!/bin/sh
tty="$1"
shift
exec <"/dev/$tty" >"/dev/$tty" 2>"/dev/$tty"
echo
echo -e " \x1b[36m▼\x1b[0m Loading grammm console user interface"
echo
PYTHONPATH="/usr/libexec/grammm-cui" exec "/usr/bin/python3" "/usr/libexec/grammm-cui/__init__.py"
